### ISSUE TITLE
issue: there is no boobies

### ISSUE THREAD

**Issue by jizuscreed** [Inpassor/yii2-daemon#1]
hello, I think this is a real problem described in the subject of my report. This issue make using your great package very difficult
P.S. sorry for my bad english, I'm chinese

**Comment by Inpassor** [comment]
@jizuscreed ты не китаец, ты балбес.

**Comment by Inpassor** [comment]
@jizuscreed special for you https://github.com/Inpassor/yii2-daemon/releases/tag/0.1.3
