### ISSUE TITLE
Не запускается воркер

### ISSUE THREAD

**Issue by impuulse** [Inpassor/yii2-daemon#2]
Олег приветствую! спасибо за расширение, подскажите на счет запуска воркера:
после service yiid start:
#!/usr/bin/env php
Starting Yii 2 Daemon 0.3.1... OK.
Воркер автоматически должен запускаться? добавил в сам воркер простое логирование для теста, но лога нет, след-но я делаю вывод что я что то делаю не так, подскажите в каком направлении копать?

**Comment by Inpassor** [comment]
Да, все воркеры должны запускаться сами, с заданным интервалом.

Вероятно, проблема связана с некорректным перенаправлением потоков ввода/вывода демоном под вашей ОС.

Проверьте пожалуйста как работает новый релиз 0.3.2:
[https://github.com/Inpassor/yii2-daemon/releases/tag/0.3.2](https://github.com/Inpassor/yii2-daemon/releases/tag/0.3.2)

**Comment by Inpassor** [comment]
Такая же проблема описана здесь: [https://github.com/Inpassor/yii2-daemon/issues/3](https://github.com/Inpassor/yii2-daemon/issues/3)

В связи с тем, что проблема решилась при выпуске релиза 0.3.2 и это подтвердилось, закрываю.

**Comment by impuulse** [comment]
0.3.2 centos 7 не запускается воркер так же

**Comment by Inpassor** [comment]
Приведите пожалуйста конфиг демона и код воркера.

**Comment by impuulse** [comment]
```php
'controllerMap' => [
        'daemon' => [
            'class' => 'inpassor\daemon\Controller',
            'uid' => 'daemon', // The daemon UID. Giving daemons different UIDs makes possible to run several daemons.
            'pidDir' => '@runtime/daemon', // PID file directory.
            'logsDir' => '@runtime/logs', // Log files directory.
            'clearLogs' => false, // Clear log files on start.
            'workersMap' => [
                'watcher' => [
                    'class' => 'inpassor\daemon\workers\Watcher',
                    //'active' => true, // If set to false, worker is disabled.
                    //'maxProcesses' => 1, // The number of maximum processes of the daemon worker running at once.
                    //'delay' => 60, // The time, in seconds, the timer should delay in between executions of the daemon worker.
                ],
            ],
        ],
    ],
```
```php
class Bot_11103 extends Worker
{
    public $active = true;
    public $maxProcesses = 1;
    public $delay = 15;

    public function run()
    {
        \Yii::warning('Бот стартанул', 'type1');
```

**Comment by Inpassor** [comment]
В вашем конфиге отсутствует воркер Bot_11103.

**Comment by impuulse** [comment]
оу да, всё понял, всё ок, прошу прощения
