### ISSUE TITLE
Как задать динамичесикй интервал ? 

### ISSUE THREAD

**Issue by impuulse** [Inpassor/yii2-daemon#4]
приветствую, задаю delay в конструкторе по своей специфике, он нужен разный в зависимости от условий, но после запуска демона, он берет лишь первый заданный, затем delay уже не меняется. Можно что то с этим придумать или уже есть решение?

**Comment by Inpassor** [comment]
Добрый день!
Такой возможности я не предусматривал, но в принципе можно сделать динамическое считывание конфигов воркеров, если это действительно необходимо. Для моих нужд это не нужно :) И к тому же такой функционал наверняка создаст дополнительную трату ресурсов.

Самое простое - это сделать воркер со статическим delay, например, в 1 секунду, и уже в нем делать проверку на динамическое условие в методе run(). При выполнении условия продолжать работу воркера, в обратном случае просто делать return.

**Comment by impuulse** [comment]
> Самое простое - это сделать воркер со статическим delay, например, в 1 секунду, и уже в нем делать проверку на динамическое условие в методе run(). При выполнении условия продолжать работу воркера, в обратном случае просто делать return.

А можно пожалуйста простейший пример ? Очень нужно, заранее благодарен!

**Comment by Inpassor** [comment]
Простейший пример, использующий БД redis:

1. Добавляем в composer.json зависимость от пакета yii2-redis:

```
    "require": {
        ...
        "yiisoft/yii2-redis": "*",
        ...
    },
```

2. Делаем composer update.

3. В основной конфиг в секцию components добавляем redis connection:

```
    'components' => [
        ...
        'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'localhost',
            'port' => 6379,
            'database' => 0,
        ],
        ...
    ],
```

4. Создаем модель для хранения данных воркера в БД redis:

app\models\TestWorkerData.php :

```
<?php

namespace app\models;

class TestWorkerData extends \yii\redis\ActiveRecord
{

    public function attributes()
    {
        return [
            'id',
            'delay',
        ];
    }

}
```

5. Код воркера:

app\daemon\TestWorker.php :

```
<?php

namespace app\daemon;

use \app\models\TestWorkerData;

class TestWorker extends \inpassor\daemon\Worker
{

    public $delay = 1;

    public function run()
    {
        $data = TestWorkerData::findOne(1);
        if (!$data) {
            $data = new TestWorkerData([
                'id' => 1,
                'delay' => 10, // Тут устанавливаем начальное значение задержки
            ]);
        }

        // TODO: некое условие, по которому меняем задержку

        // Уменьшаем задержку на 1
        $data->delay--;

        $data->save(false);

        // Если задержка больше 0 - не выполняем работу
        if ($data->delay > 0) {
            return;
        }

        // TODO: worker job
    }

}
```

6. Прописываем воркер в конфиге демона.

**Comment by impuulse** [comment]
> // TODO: некое условие, по которому меняем задержку

так а как поменять то задержку тут?

я в конструкторе делаю delay = rand(5,10) - но срабатывает только первое рэндомное число, далее не рэндомится, в run() delay вроде нельзя задать, или я что то делаю не так?

**Comment by Inpassor** [comment]
```
<?php

namespace app\daemon;

use \app\models\TestWorkerData;

class TestWorker extends \inpassor\daemon\Worker
{

    public $delay = 1;

    public function run()
    {
        $data = TestWorkerData::findOne(1);
        if (!$data) {
            $data = new TestWorkerData([
                'id' => 1,
                'delay' => rand(5, 10),
            ]);
        }

        // Если задержка больше 0 - не выполняем работу
        if ($data->delay > 0) {
            // Уменьшаем задержку на 1
            $data->delay--;
            $data->save(false);
            return;
        }

        $data->delay = rand(5, 10);
        $data->save(false);

        // TODO: worker job
    }

}
```

Как-то так.

**Comment by impuulse** [comment]
Я видимо что то не понимаю, а как воркер узнает о delay хранившемся в моделе redis-a? Где взаимосвязь? Спасибо за ответ.

**Comment by Inpassor** [comment]
Код модели тут - \app\models\TestWorkerData

Использование данных вот, в методе run():

```
        $data = TestWorkerData::findOne(1);
        if (!$data) {
            $data = new TestWorkerData([
                'id' => 1,
                'delay' => rand(5, 10),
            ]);
        }
```

**Comment by impuulse** [comment]
как delay из модели назначится delay воркера, ведь нет переназначения public $delay ?

**Comment by impuulse** [comment]
Спасибо дошло!)
